#!/usr/bin/env python3
"""Generate kys_manifest.js — a JS file defining KYS_MANIFEST with dirs/files arrays.
Only writes if content changed, to avoid triggering unnecessary rebuilds."""
import json, os, sys

def main():
    game_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', 'work', 'game-dev')
    game_dir = os.path.normpath(game_dir)
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), 'kys_manifest.js')
    mount = "/game"

    dirs = [mount]  # root mount point first
    files = []
    for root, dirnames, filenames in os.walk(game_dir):
        rel = os.path.relpath(root, game_dir).replace('\\', '/')
        if rel == '.':
            rel = ''
        for d in sorted(dirnames):
            p = f"{rel}/{d}" if rel else d
            dirs.append(f"{mount}/{p}")
        for f in sorted(filenames):
            p = f"{rel}/{f}" if rel else f
            files.append(f"{mount}/{p}")

    new_content = (
        f"// Auto-generated by gen_manifest.py -- {len(dirs)} dirs, {len(files)} files\n"
        f"var KYS_MANIFEST = {{\n"
        f"  dirs: {json.dumps(dirs)},\n"
        f"  files: {json.dumps(files)}\n"
        f"}};\n"
    )

    try:
        with open(out_path, "rb") as fh:
            old_content = fh.read()
        if old_content == new_content.encode("utf-8"):
            print(f"gen_manifest: {out_path} is up to date ({len(dirs)} dirs, {len(files)} files)")
            return
    except FileNotFoundError:
        pass

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(new_content)
    print(f"gen_manifest: wrote {out_path} ({len(dirs)} dirs, {len(files)} files)")

if __name__ == '__main__':
    main()
