#!/usr/bin/env python3
"""Generate wasm_manifest.inc — a C++ raw string literal listing dirs (D) and files (F).
Only writes if content changed, to avoid triggering unnecessary rebuilds."""
import os, sys

def main():
    game_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', 'work', 'game-dev')
    game_dir = os.path.normpath(game_dir)
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), 'wasm_manifest.inc')
    mount = "/game"

    dirs = []
    files = []
    for root, dirnames, filenames in os.walk(game_dir):
        rel = os.path.relpath(root, game_dir).replace('\\', '/')
        if rel == '.':
            rel = ''
        for d in sorted(dirnames):
            p = f"{rel}/{d}" if rel else d
            dirs.append(p)
        for f in sorted(filenames):
            p = f"{rel}/{f}" if rel else f
            files.append(p)

    lines = []
    lines.append(f"// Auto-generated by gen_manifest.py -- {len(dirs)} dirs, {len(files)} files")
    lines.append(f'static const char* wasm_manifest_data = R"MANIFEST(')
    for d in dirs:
        lines.append(f"D {mount}/{d}")
    for f in files:
        lines.append(f"F {mount}/{f}")
    lines.append(')MANIFEST";')
    lines.append("")

    new_content = "\n".join(lines)

    try:
        with open(out_path, "rb") as fh:
            old_content = fh.read()
        if old_content == new_content.encode("utf-8"):
            print(f"gen_manifest: {out_path} is up to date ({len(dirs)} dirs, {len(files)} files)")
            return
    except FileNotFoundError:
        pass

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(new_content)
    print(f"gen_manifest: wrote {out_path} ({len(dirs)} dirs, {len(files)} files)")

if __name__ == '__main__':
    main()
