角色:
  # 费用: 1
  - 63  # 程英
  - 84  # 霍都
  - 160  # 達爾巴
  - 161  # 李莫愁
  - 47  # 阿紫
  - 104  # 阿朱
  - 105  # 阿碧
  - 72  # 田歸農
  - 4  # 閻基
  - 106  # 王元霸
  - 605  # 趙敏
  - 123  # 馬鈺
  - 124  # 譚處端
  # 费用: 2
  - 54  # 袁承志
  - 37  # 狄云
  - 97  # 血刀老祖
  - 56  # 黃蓉
  - 44  # 岳老三
  - 48  # 游坦之
  - 99  # 葉二娘
  - 100  # 云中鶴
  - 102  # 枯榮
  - 115  # 蘇星河
  - 29  # 田伯光
  - 126  # 王處一
  - 125  # 劉處玄
  # 费用: 3
  - 55  # 郭靖
  - 68  # 丘處機
  - 59  # 小龍女
  - 46  # 丁春秋
  - 51  # 慕容復
  - 53  # 段譽
  - 70  # 玄慈
  - 98  # 段延慶
  - 103  # 鳩摩智
  - 113  # 慕容博
  - 14  # 韋一笑
  - 593  # 周芷若
  - 6  # 滅絕
  - 10  # 范遙
  - 18  # 成崑
  - 19  # 岳不群
  # 费用: 4
  - 57  # 黃藥師
  - 64  # 周伯通
  - 65  # 一燈
  - 69  # 洪七公
  - 58  # 楊過
  - 62  # 金輪法王
  - 49  # 虛竹
  - 50  # 喬峰
  - 117  # 天山童姥
  - 118  # 李秋水
  - 13  # 謝遜
  - 12  # 殷天正
  # 费用: 5
  - 129  # 王重陽
  - 114  # 掃地老僧
  - 116  # 無崖子
  - 27  # 東方不敗
  - 604  # 黃裳
