远征挑战:
  - 名称: "聚贤庄内"
    描述: "挑战乔峰"
    敌人: [[50, 3]]
    奖励:
      - 类型: 获取金币
        数值: 10
      - 类型: 升星1到2
        最高费用: 2
      - 类型: 获取棋子
        最高费用: 3

  - 名称: "慕容世家"
    描述: "姑苏慕容一族的挑战"
    敌人: [[51, 1], [104, 2], [105, 2], [113, 1]]
    奖励:
      - 类型: 获取内功
        最高层级: 1
      - 类型: 获取棋子
        最高费用: 4
      - 类型: 升星1到2
        最高费用: 3

  - 名称: "江南七怪"
    描述: "江南七怪齐聚"
    敌人: [[130, 2], [131, 2], [132, 2], [133, 2], [134, 2], [135, 2], [136, 2]]
    奖励:
      - 类型: 获取金币
        数值: 25
      - 类型: 升星2到3
        最高费用: 2
      - 类型: 获取装备
        最高层级: 2

  - 名称: "五绝论剑"
    描述: "与五绝级别的高手交锋"
    敌人: [[57, 2], [60, 2], [69, 2], [65, 2], [64, 2]]
    奖励:
      - 类型: 升星2到3
        最高费用: 3
      - 类型: 获取内功
        最高层级: 2
      - 类型: 获取装备
        最高层级: 3

  - 名称: "武林至尊"
    描述: "挑战最强角色"
    敌人:
      - 角色ID: 129  # 王重陽
        星级: 2
        武器: 38  # 周公劍
      - 角色ID: 114  # 掃地老僧
        星级: 2
      - 角色ID: 116  # 無崖子
        星级: 2
      - 角色ID: 50  # 喬峰
        星级: 3
      - 角色ID: 117  # 天山童姥
        星级: 3
      - 角色ID: 62  # 金輪法王
        星级: 3
      - 角色ID: 58  # 楊過
        星级: 3
    奖励:
      - 类型: 升星2到3
        最高费用: 4
      - 类型: 获取棋子
        最高费用: 5
      - 类型: 获取金币
        数值: 30

  - 名称: "江湖侠客"
    描述: "发福利挑战关卡"
    敌人: 
      - [70, 3] # 玄慈
      - [67, 2] # 裘千仞
      - [117, 2] # 天山童姥
      - [113, 3] # 慕容博
      - [112, 2] # 蕭遠山
      - [37, 3] # 狄云
      - [53, 3] # 段誉
      - [97, 3] # 血刀老祖 
    奖励:
      - 类型: 获取金币
        数值: 30
      - 类型: 获取装备
        最高层级: 3

  - 名称: "万剑齐发"
    描述: "挑战前代剑系角色"
    敌人:
      - 角色ID: 131  # 朱聰
        星级: 3
        武器: 37  # 倚天劍
      - 角色ID: 135  # 全金發
        星级: 3
        武器: 37  # 倚天劍
      - 角色ID: 136  # 韓小瑩
        星级: 3
        武器: 37  # 倚天劍
      - 角色ID: 63  # 程英
        星级: 3
        武器: 37  # 倚天劍
      - 角色ID: 54  # 袁承志
        星级: 3
        武器: 37  # 倚天劍
      - 角色ID: 99  # 葉二娘
        星级: 3
        武器: 37  # 倚天劍
      - 角色ID: 68  # 丘處機
        星级: 3
        武器: 37  # 倚天劍
      - 角色ID: 59  # 小龍女
        星级: 3
        武器: 37  # 倚天劍
      - 角色ID: 51  # 慕容復
        星级: 3
        武器: 37  # 倚天劍
    奖励:
      - 类型: 获取金币
        数值: 30
      - 类型: 获取指定装备
        装备ID: 37

  - 名称: "六大宗师"
    描述: "六大宗师齐出手"
    敌人:
      - 角色ID: 114  # 掃地老僧
        星级: 3
      - 角色ID: 5 # 張三丰
        星级: 3
      - 角色ID: 27 # 東方不敗
        星级: 3
      - 角色ID: 604 # 黃裳
        星级: 3
      - 角色ID: 116  # 無崖子
        星级: 3
      - 角色ID: 129  # 王重陽
        星级: 3
    奖励:
      - 类型: 获取金币
        数值: 30
      - 类型: 升星1到2
        最高费用: 5

  - 名称: "五费神通"
    描述: "前代版本，五费亲自部署"
    敌人:
      - 角色ID: 116  # 无崖子
        星级: 3
        武器: 57  # 犽月
        防具: 60  # 金絲背心
      - 角色ID: 118  # 李秋水
        星级: 3
        武器: 41  # 凝碧劍
        防具: 60  # 金絲背心
      - 角色ID: 117  # 天山童姥
        星级: 3
        武器: 41  # 凝碧劍
      - 角色ID: 49  # 虚竹
        星级: 3
        武器: 50  # 伏魔杵
        防具: 60  # 金絲背心
      - 角色ID: 115  # 蘇星河
        星级: 3
        武器: 50  # 伏魔杵
        防具: 60  # 金絲背心
      - 角色ID: 45  # 薛慕華
        星级: 3
      - 角色ID: 114  # 扫地
        星级: 3
        武器: 50  # 伏魔杵
        防具: 62  # 佛心甲
      - 角色ID: 103  # 鳩摩智
        星级: 3
        武器: 56  # 玄鐵菜刀
        防具: 62  # 佛心甲
      - 角色ID: 70  # 玄慈
        星级: 3
        武器: 50  # 伏魔杵
        防具: 62  # 佛心甲
      - 角色ID: 68  # 丘處機
        星级: 3
        武器: 55  # 神山劍
        防具: 58  # 軟蝟甲
      - 角色ID: 64  # 周伯通
        星级: 3
        武器: 49  # 打狗棒
        防具: 58  # 軟蝟甲
      - 角色ID: 129  # 王重陽
        星级: 3
        武器: 55  # 神山劍
        防具: 58  # 軟蝟甲
    奖励:
      - 类型: 获取金币
        数值: 30

  - 名称: "爆炸卡车"
    描述: "杂鱼的逆袭"
    敌人:
      - 角色ID: 160  # 達爾巴
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 106 # 王元霸
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 610  # 俞岱巖
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 172 # 莫聲谷
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 72 # 田歸農
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 608 # 張松溪
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 126 # 王處一
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 124 # 譚處端
        星级: 3
        武器: 49  # 打狗棒
        防具: 58  # 軟蝟甲
      - 角色ID: 172 # 莫聲谷
        星级: 3
        武器: 55  # 神山劍
        防具: 58  # 軟蝟甲
      - 角色ID: 172 # 莫聲谷
        星级: 3
        武器: 57  # 犽月
        防具: 58  # 軟蝟甲
      - 角色ID: 172 # 莫聲谷
        星级: 3
        武器: 236  # 真武劍
        防具: 58  # 軟蝟甲
      - 角色ID: 172 # 莫聲谷
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
    奖励:
      - 类型: 获取金币
        数值: 1

  - 名称: "钢铁雄躯"
    描述: "肉盾和奶妈"
    敌人:
      - 角色ID: 114  # 掃地老僧
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 103  # 鳩摩智
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 70  # 玄慈
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 9 # 張無忌
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 5 # 張三丰
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 603 # 郭襄
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 611 # 無色禪師
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 129  # 王重陽
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 2 # 程靈素
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 28 # 平一指
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 16 # 胡青牛
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
      - 角色ID: 45  # 薛慕華
        星级: 3
        武器: 36  # 玄鐵劍
        防具: 58  # 軟蝟甲
    奖励:
      - 类型: 获取金币
        数值: 1
