棋手天賦:
  神兵:
    說明: 獲得更多、更高階的裝備獎勵，並可在終局開啟神兵商店。
    可使用神兵商店: true
  晚成:
    說明: 棋子的勝場成長受星級倍率及其他百分比效果加成。
    勝場成長受加成比例: 100
  賭徒:
    說明: 投資低費棋子，付費刷新累積賭運，於致命傷害時搏取生機。
    開局額外禁棋:
      次數: 8
      最低費用: 1
      最高費用: 2
    賭運:
      累積截止關卡: 20
      目標最低費用: 1
      目標最高費用: 3
      每次增加層數: 1
      每層觸發機率百分點: 20
      層數上限: 5
      觸發後生命: 1
      無敵幀數: 100
  中堅:
    說明: 非三費友軍的額外星級提供開場內力，三費棋子升至二星後下次商店必刷新。
    目標費用: 3
    額外星級加成:
      每顆開場內力: 15
      計算上限: 6
    刷新保證:
      觸發星級: 2
      每次數量: 1
