- 费用: 1
  角色:
    - 130  # 柯鎮惡
    - 131  # 朱聰
    - 132  # 韓寶駒
    - 133  # 南希仁
    - 134  # 張阿生
    - 135  # 全金發
    - 136  # 韓小瑩
    - 63  # 程英
    - 84  # 霍都
    - 160  # 達爾巴
    - 161  # 李莫愁
    - 45  # 薛慕華
    - 47  # 阿紫
    - 104  # 阿朱
    - 105  # 阿碧
- 费用: 2
  角色:
    - 54  # 袁承志
    - 37  # 狄云
    - 97  # 血刀老祖
    - 56  # 黃蓉
    - 44  # 岳老三
    - 48  # 游坦之
    - 99  # 葉二娘
    - 100  # 云中鶴
    - 102  # 枯榮
    - 115  # 蘇星河
- 费用: 3
  角色:
    - 55  # 郭靖
    - 67  # 裘千仞
    - 68  # 丘處機
    - 59  # 小龍女
    - 46  # 丁春秋
    - 51  # 慕容復
    - 53  # 段譽
    - 70  # 玄慈
    - 98  # 段延慶
    - 103  # 鳩摩智
    - 112  # 蕭遠山
    - 113  # 慕容博
- 费用: 4
  角色:
    - 57  # 黃藥師
    - 60  # 歐陽鋒
    - 64  # 周伯通
    - 65  # 一燈
    - 69  # 洪七公
    - 58  # 楊過
    - 62  # 金輪法王
    - 49  # 虛竹
    - 50  # 喬峰
    - 117  # 天山童姥
    - 118  # 李秋水
- 费用: 5
  角色:
    - 129  # 王重陽
    - 114  # 掃地老僧
    - 116  # 無崖子
