羁绊:
  - 名称: 江南七怪
    成员:
      - 130  # 柯鎮惡
      - 131  # 朱聰
      - 132  # 韓寶駒
      - 133  # 南希仁
      - 134  # 張阿生
      - 135  # 全金發
      - 136  # 韓小瑩
    星级羁绊加成: true
    阈值:
      - 人数: 3
        名称: 七怪合力
        效果:
          - 类型: 防御加成
            数值: 50
          - 类型: 固定减伤
            数值: 15
      - 人数: 5
        名称: 师徒之情
        效果:
          - 类型: 防御加成
            数值: 70
          - 类型: 固定减伤
            数值: 20
      - 人数: 7
        名称: 七侠齐心
        效果:
          - 类型: 防御加成
            数值: 100
          - 类型: 固定减伤
            数值: 25
          - 类型: 格挡几率
            数值: 18

  - 名称: 神雕侠侣
    成员:
      - 58  # 楊過
      - 59  # 小龍女
    阈值:
      - 人数: 2
        名称: 玉女素心
        效果:
          - 类型: 攻击百分比
            数值: 125
            触发: 友方低血狂暴
            触发参数: 30
            持续帧数: 200
            次数: 1

  - 名称: 姑苏慕容
    成员:
      - 104  # 阿朱
      - 105  # 阿碧
      - 51  # 慕容復
      - 113  # 慕容博
    阈值:
      - 人数: 2
        名称: 参合庄
        效果:
          - 类型: 技能反弹
            数值: 28
          - 类型: 眩晕
            触发: 被击中时概率
            触发参数: 25
            数值: 30
      - 人数: 4
        名称: 以彼之道还施彼身
        效果:
          - 类型: 技能反弹
            数值: 45
          - 类型: 眩晕
            触发: 被击中时概率
            触发参数: 35
            数值: 40
          - 类型: 伤害降低
            数值: 30
            附加参数: 70

  - 名称: 天龙三兄弟
    成员:
      - 53  # 段譽
      - 49  # 虛竹
      - 50  # 喬峰
    阈值:
      - 人数: 2
        名称: 义结金兰
        效果:
          - 类型: 生命加成
            数值: 300
          - 类型: 命中回蓝
            数值: 15
          - 类型: 僵直抗性
            数值: 30
      - 人数: 3
        名称: 天龙聚首
        效果:
          - 类型: 生命加成
            数值: 500
          - 类型: 命中回蓝
            数值: 30
          - 类型: 僵直抗性
            数值: 60

  - 名称: 丐帮
    成员:
      - 69  # 洪七公
      - 48  # 游坦之
      - 56  # 黃蓉
      - 50  # 喬峰
    阈值:
      - 人数: 2
        名称: 行乞
        效果:
          - 类型: 金币加成
            数值: 1
      - 人数: 4
        名称: 丐帮长老
        效果:
          - 类型: 金币加成
            数值: 2

  - 名称: 五绝
    成员:
      - 57  # 黃藥師
      - 60  # 歐陽鋒
      - 69  # 洪七公
      - 65  # 一燈
      - 129 # 王重陽
    阈值:
      - 人数: 2
        名称: 华山论剑
        效果:
          - 类型: 攻击百分比
            数值: 16
          - 类型: 防御加成
            数值: 60
          - 类型: 速度加成
            数值: 30
      - 人数: 4
        名称: 天下五绝
        效果:
          - 类型: 攻击百分比
            数值: 32
          - 类型: 防御加成
            数值: 150
          - 类型: 速度加成
            数值: 30
          - 类型: 僵直护盾
            数值: 120

  - 名称: 逍遥
    成员:
      - 45  # 薛慕華
      - 115  # 蘇星河
      - 46  # 丁春秋
      - 49  # 虛竹
      - 117  # 天山童姥
      - 118  # 李秋水
      - 116  # 無崖子
    阈值:
      - 人数: 2
        名称: 逍遥门徒
        效果:
          - 类型: 僵直抗性
            数值: 20
          - 类型: 冷却缩减
            数值: 25
          - 类型: 回蓝加成
            数值: 20
      - 人数: 4
        名称: 逍遥无相
        效果:
          - 类型: 僵直抗性
            数值: 40
          - 类型: 冷却缩减
            数值: 35
          - 类型: 回蓝加成
            数值: 35
      - 人数: 6
        名称: 逍遥至尊
        效果:
          - 类型: 僵直抗性
            数值: 60
          - 类型: 冷却缩减
            数值: 45
          - 类型: 回蓝加成
            数值: 50
          - 类型: 技能后无敌
            数值: 15

  - 名称: 大理段氏
    成员:
      - 102  # 枯榮
      - 53  # 段譽
      - 98  # 段延慶
      - 65  # 一燈
    阈值:
      - 人数: 2
        名称: 一阳指传承
        效果:
          - 类型: 连击增伤
            数值: 5
            附加参数: 10
          - 类型: 眩晕
            数值: 25
            触发: 攻击命中时概率
            触发参数: 25
      - 人数: 4
        名称: 六脉神剑
        效果:
          - 类型: 连击增伤
            数值: 10
            附加参数: 10
          - 类型: 眩晕
            数值: 35
            触发: 攻击命中时概率
            触发参数: 35

  - 名称: 四大恶人
    成员:
      - 98  # 段延慶
      - 99  # 葉二娘
      - 44  # 岳老三
      - 100  # 云中鶴
    阈值:
      - 人数: 2
        名称: 恶人当道
        效果:
          - 类型: 攻击百分比
            数值: 20
          - 类型: 防御削减
            数值: 10
          - 类型: 每N次双倍
            数值: 4
      - 人数: 4
        名称: 四大恶人
        效果:
          - 类型: 攻击百分比
            数值: 30
          - 类型: 防御削减
            数值: 20
          - 类型: 每N次双倍
            数值: 3

  - 名称: 桃花岛
    成员:
      - 63  # 程英
      - 56  # 黃蓉
      - 55  # 郭靖
      - 57  # 黃藥師
    阈值:
      - 人数: 2
        名称: 桃花门徒
        效果:
          - 类型: 速度加成
            数值: 20
          - 类型: 闪避几率
            数值: 20
      - 人数: 4
        名称: 桃花岛主
        效果:
          - 类型: 速度加成
            数值: 30
          - 类型: 闪避几率
            数值: 30
          - 类型: 闪避后暴击
            数值: 1

  - 名称: 少林寺
    成员:
      - 70  # 玄慈
      - 103  # 鳩摩智
      - 114  # 掃地老僧
      - 611 # 無色禪師
      - 18 # 成崑
    阈值:
      - 人数: 2
        名称: 少林弟子
        效果:
          - 类型: 生命百分比
            数值: 18
          - 类型: 生命回复
            数值: 3
            附加参数: 80
      - 人数: 4
        名称: 扫地神功
        效果:
          - 类型: 生命百分比
            数值: 30
          - 类型: 生命回复
            数值: 3
            附加参数: 55
          - 类型: 同敌减伤
            数值: 6
            附加参数: 5


  - 名称: 全真教
    成员:
      - 68  # 丘處機
      - 64  # 周伯通
      - 129  # 王重陽
      - 123 # 馬鈺
      - 126 # 王處一
      - 124 # 譚處端
      - 125 # 劉處玄
    阈值:
      - 人数: 3
        名称: 先天功
        效果:
          - 类型: 护盾生命比
            数值: 30
          - 类型: 临时攻击加成
            数值: 50
            持续帧数: 75
            触发: 护盾爆炸时
          - 类型: 自动绝招
            数值: 1
            触发: 护盾爆炸时
      - 人数: 5
        名称: 七星聚真
        效果:
          - 类型: 护盾生命比
            数值: 40
          - 类型: 临时攻击加成
            数值: 50
            持续帧数: 75
            触发: 护盾爆炸时
          - 类型: 自动绝招
            数值: 1
            触发: 护盾爆炸时
          - 类型: 回内力
            数值: 50
            触发: 护盾爆炸时
          - 类型: 护盾重获
            数值: 4
      - 人数: 7
        名称: 全真北斗
        效果:
          - 类型: 护盾生命比
            数值: 50
          - 类型: 临时攻击加成
            数值: 50
            持续帧数: 75
            触发: 护盾爆炸时
          - 类型: 自动绝招
            数值: 1
            触发: 护盾爆炸时
          - 类型: 回内力
            数值: 50
            触发: 护盾爆炸时
          - 类型: 护盾重获
            数值: 3

  - 名称: 蒙古三雄
    成员:
      - 84  # 霍都
      - 160  # 達爾巴
      - 62  # 金輪法王
    阈值:
      - 人数: 2
        名称: 蒙古勇士
        效果:
          - 类型: 生命加成
            数值: 280
          - 类型: 攻击加成
            数值: 35
      - 人数: 3
        名称: 龙象之力
        效果:
          - 类型: 生命加成
            数值: 560
          - 类型: 攻击加成
            数值: 70

  - 名称: 连城诀
    成员:
      - 37  # 狄云
      - 97  # 血刀老祖
    阈值:
      - 人数: 2
        名称: 绝境求生
        效果:
          - 类型: 攻击加成
            数值: 100
            触发: 低血量
            触发参数: 50
          - 类型: 回血
            数值: 20
            触发: 低血量
            触发参数: 20
            次数: 1
          - 类型: 攻击百分比
            数值: 30
            触发: 低血量
            触发参数: 40

  - 名称: 毒宗
    成员:
      - 161  # 李莫愁
      - 47  # 阿紫
      - 46  # 丁春秋
      - 60  # 歐陽鋒
      - 2 # 程靈素
      - 48 # 游坦之
    阈值:
      - 人数: 2
        名称: 毒手
        效果:
          - 类型: 中毒伤害
            数值: 7
            附加参数: 3
          - 类型: 中毒增伤
            数值: 20
          - 类型: 吸取内力
            数值: 7
      - 人数: 4
        名称: 天下毒尊
        效果:
          - 类型: 中毒伤害
            数值: 10
            附加参数: 5
          - 类型: 中毒增伤
            数值: 48
          - 类型: 吸取内力
            数值: 13

  - 名称: 射雕英雄
    成员:
      - 55  # 郭靖
      - 58  # 楊過
      - 69  # 洪七公
    阈值:
      - 人数: 3
        名称: 为国为民
        效果:
          - 类型: 生命加成
            数值: 500
          - 类型: 击杀回血
            数值: 22
          - 类型: 击杀无敌
            数值: 90

  - 名称: 武林外道
    成员:
      - 67  # 裘千仞
      - 103  # 鳩摩智
      - 62  # 金輪法王
      - 27 # 東方不敗
    阈值:
      - 人数: 3
        名称: 以力破巧
        效果:
          - 类型: 防御百分比
            数值: 36
          - 类型: 技能伤害
            数值: 22
          - 类型: 击杀增攻
            数值: 110

  - 名称: 剑客
    成员:
      - 131  # 朱聰
      - 135  # 全金發
      - 136  # 韓小瑩
      - 54  # 袁承志
      - 99  # 葉二娘
      - 68  # 丘處機
      - 59  # 小龍女
      - 51  # 慕容復
      - 6 # 滅絕師太
      - 600 # 殷梨亭
      - 19 # 岳不群
    阈值:
      - 人数: 3
        名称: 剑意初成
        效果:
          - 类型: 固定加伤
            数值: 15
          - 类型: 穿甲
            数值: 18
            触发: 攻击命中时概率
            触发参数: 100
      - 人数: 5
        名称: 万剑归宗
        效果:
          - 类型: 固定加伤
            数值: 30
          - 类型: 穿甲
            数值: 36
            触发: 攻击命中时概率
            触发参数: 100
      - 人数: 7
        名称: 剑神
        效果:
          - 类型: 固定加伤
            数值: 45
          - 类型: 穿甲
            数值: 54
            触发: 攻击命中时概率
            触发参数: 100
          - 类型: 斩杀
            数值: 20
            触发: 攻击命中时概率
            触发参数: 15

  - 名称: 拳师
    成员:
      - 134  # 張阿生
      - 84  # 霍都
      - 54  # 袁承志
      - 102  # 枯榮
      - 67  # 裘千仞
      - 70  # 玄慈
      - 112  # 蕭遠山
      - 12 # 殷天正
      - 171 # 宋遠橋
      - 609 # 俞蓮舟
      - 64  # 周伯通
      - 50 # 喬峰
      - 5 # 張三丰
    阈值:
      - 人数: 3
        名称: 拳意
        效果:
          - 类型: 攻击百分比
            数值: 28
          - 类型: 伤害减免
            数值: 10
          - 类型: 击退几率
            数值: 12
      - 人数: 5
        名称: 拳王
        效果:
          - 类型: 攻击百分比
            数值: 40
          - 类型: 伤害减免
            数值: 17
          - 类型: 击退几率
            数值: 20
      - 人数: 7
        名称: 拳神
        效果:
          - 类型: 攻击百分比
            数值: 52
          - 类型: 伤害减免
            数值: 24
          - 类型: 击退几率
            数值: 20
          - 类型: 封内
            数值: 50
            触发: 攻击命中时概率
            触发参数: 25

  - 名称: 奇门
    成员:
      - 130  # 柯鎮惡
      - 132  # 韓寶駒
      - 133  # 南希仁
      - 44  # 岳老三
      - 125 # 劉處玄
      - 604 # 黃裳
      - 27 # 東方不敗
    阈值:
      - 人数: 2
        名称: 奇门异术
        效果:
          - 类型: 暴击几率
            数值: 35
      - 人数: 4
        名称: 奇门大成
        效果:
          - 类型: 暴击几率
            数值: 35
          - 类型: 暴击伤害
            数值: 300

  - 名称: 刀客
    成员:
      - 97  # 血刀老祖
      - 29 # 田伯光
      - 106 # 王元霸
      - 589 # 胡一刀
      - 1 # 胡斐
      - 4 # 閻基
      - 103  # 鳩摩智
      - 10 # 范遙
      - 37  # 狄云
    阈值:
      - 人数: 3
        名称: 快刀
        效果:
          - 类型: 冷却缩减
            数值: 28
          - 类型: 流血
            数值: 11
            附加参数: 1
          - 类型: 流血持续
            数值: 1
      - 人数: 5
        名称: 狂刀
        效果:
          - 类型: 冷却缩减
            数值: 28
          - 类型: 流血
            数值: 11
            附加参数: 2
          - 类型: 流血持续
            数值: 1
      - 人数: 7
        名称: 血刀
        效果:
          - 类型: 冷却缩减
            数值: 28
          - 类型: 流血
            数值: 11
            附加参数: 3
          - 类型: 流血持续
            数值: 1
          - 类型: 受伤无敌
            数值: 7

  - 名称: 红颜
    成员:
      - 47  # 阿紫
      - 104  # 阿朱
      - 105  # 阿碧
      - 56  # 黃蓉
      - 118  # 李秋水
      - 593 # 周芷若
      - 605 # 趙敏
      - 607 # 黛綺絲
      - 2 # 程靈素
      - 161 # 李莫愁
    阈值:
      - 人数: 3
        名称: 巾帼
        效果:
          - 类型: 固定治疗光环
            数值: 20
            附加参数: 120
          - 类型: 冷却延长反击
            数值: 30
            附加参数: 50
      - 人数: 5
        名称: 红颜知己
        效果:
          - 类型: 固定治疗光环
            数值: 25
            附加参数: 120
          - 类型: 受治疗加速
            数值: 30
          - 类型: 冷却延长反击
            数值: 50
            附加参数: 60
      - 人数: 7
        名称: 倾国倾城
        效果:
          - 类型: 固定治疗光环
            数值: 30
            附加参数: 120
          - 类型: 受治疗加速
            数值: 50
          - 类型: 冷却延长反击
            数值: 70
            附加参数: 70
          - 类型: 攻击冷却延长
            数值: 10

  - 名称: 琴棋书画
    成员:
      - 115  # 蘇星河
      - 57  # 黃藥師
      - 606 # 張翠山
      - 63  # 程英
      - 116  # 無崖子
    阈值:
      - 人数: 2
        名称: 博学多才
        效果:
          - 类型: 冷却缩减
            数值: 12
          - 类型: 技能伤害
            数值: 24

  - 名称: 独行
    成员:
      - 67  # 裘千仞
      - 98  # 段延慶
      - 112  # 蕭遠山
      - 60  # 歐陽鋒
      - 29 # 田伯光
      - 604 # 黃裳
      - 28 # 平一指
      - 114  # 掃地老僧
    反向羁绊: true
    阈值:
      - 人数: 1
        名称: 绝世独立
        效果:
          - 类型: 攻击百分比
            数值: 25
          - 类型: 速度加成
            数值: 10
          - 类型: 防御百分比
            数值: 25
          - 类型: 攻击百分比
            数值: 25
            触发: 最后存活
          - 类型: 格挡几率
            数值: 15
            触发: 最后存活

  - 名称: 踏雪无痕
    成员:
      - 1 # 胡斐
      - 589 # 胡一刀
      - 14 # 韋一笑
      - 53  # 段譽
      - 27 # 東方不敗
      - 100  # 云中鶴
    阈值:
      - 人数: 2
        名称: 踏雪
        效果:
          - 类型: 速度百分比
            数值: 15
          - 类型: 滑步攻击
            数值: 1
          - 类型: 闪避几率
            数值: 5
          - 类型: 同敌闪避
            数值: 3
            附加参数: 7
      - 人数: 4
        名称: 无痕
        效果:
          - 类型: 速度百分比
            数值: 30
          - 类型: 滑步攻击
            数值: 1
          - 类型: 滑步概率提升
            数值: 15
          - 类型: 闪避几率
            数值: 5
          - 类型: 同敌闪避
            数值: 5
            附加参数: 7

  - 名称: 阴险
    成员:
      - 72 # 田歸農
      - 4 # 閻基
      - 18 # 成崑
      - 19 # 岳不群
      - 82 # 宋青書
      - 46  # 丁春秋
      - 97  # 血刀老祖
      - 161 # 李莫愁
      - 604 # 黃裳
    阈值:
      - 人数: 2
        名称: 暗算
        效果:
          - 类型: 敌方攻防削弱
            数值: 1
            附加参数: 22
          - 类型: 命中回血
            数值: 6
      - 人数: 4
        名称: 诡计
        效果:
          - 类型: 敌方攻防削弱
            数值: 2
            附加参数: 35
          - 类型: 命中回血
            数值: 12
      - 人数: 6
        名称: 阴险毒辣
        效果:
          - 类型: 敌方攻防削弱
            数值: 3
            附加参数: 48
          - 类型: 命中回血
            数值: 20

  - 名称: 宗师
    成员:
      - 5 # 張三丰
      - 114  # 掃地老僧
      - 27 # 東方不敗
      - 604 # 黃裳
      - 116  # 無崖子
      - 129  # 王重陽
    阈值:
      - 人数: 4
        名称: 出神入化
        效果:
          - 类型: 闪击
            数值: 1
          - 类型: 命中回蓝
            数值: 20

  - 名称: 明教
    成员:
      - 13 # 謝遜
      - 12 # 殷天正
      - 14 # 韋一笑
      - 607 # 黛綺絲
      - 11 # 楊逍
      - 10 # 范遙
    阈值:
      - 人数: 2
        名称: 明教教众
        效果:
          - 类型: 同袍之死
            数值: 40
          - 类型: 死亡医疗
            数值: 5
      - 人数: 4
        名称: 明教法王
        效果:
          - 类型: 同袍之死
            数值: 90
          - 类型: 死亡医疗
            数值: 5

  - 名称: 真武七截阵
    成员:
      - 5 # 張三丰
      - 171 # 宋遠橋
      - 608 # 張松溪
      - 609 # 俞蓮舟
      - 610  # 俞岱巖
      - 600 # 殷梨亭
      - 172 # 莫聲谷
      - 606 # 張翠山
      - 82 # 宋青書
    阈值:
      - 人数: 3
        名称: 三才
        效果:
          - 类型: 七截分身
            数值: 1
      - 人数: 5
        名称: 五行
        效果:
          - 类型: 七截分身
            数值: 2
      - 人数: 7
        名称: 七截
        效果:
          - 类型: 七截分身
            数值: 3

  - 名称: 内劲高手
    成员:
      - 114  # 掃地老僧
      - 123 # 馬鈺
      - 113  # 慕容博
      - 49  # 虛竹
      - 9 # 張無忌
    阈值:
      - 人数: 2
        名称: 真气护体
        效果:
          - 类型: 初次格挡
            数值: 3
          - 类型: 弹反
            数值: 15
      - 人数: 4
        名称: 内气外放
        效果:
          - 类型: 初次格挡
            数值: 6
          - 类型: 弹反
            数值: 30
          - 类型: 当前内力加伤
            数值: 35

  - 名称: 九阳传人
    成员:
      - 9 # 張無忌
      - 5 # 張三丰
      - 603 # 郭襄
      - 611 # 無色禪師
    阈值:
      - 人数: 2
        名称: 九阳初成
        效果:
          - 类型: 周期免伤
            数值: 180
            附加参数: 30
          - 类型: 周期绝招
            数值: 180
      - 人数: 4
        名称: 九阳神功
        效果:
          - 类型: 周期免伤
            数值: 180
            附加参数: 60
          - 类型: 周期绝招
            数值: 90

  - 名称: 倚天屠龙
    成员:
      - 605 # 趙敏
      - 6 # 滅絕師太
      - 603 # 郭襄
      - 13 # 謝遜
      - 593 #周芷若
    阈值:
      - 人数: 2
        名称: 倚天
        效果:
          - 类型: 连锁弹
            数值: 2
            触发: 攻击命中时概率
            触发参数: 30
            附加参数: 200
          - 类型: 绝招追加弹
            数值: 1
            触发: 绝招时
      - 人数: 4
        名称: 屠龙
        效果:
          - 类型: 连锁弹
            数值: 3
            触发: 攻击命中时概率
            触发参数: 30
            附加参数: 250
          - 类型: 绝招追加弹
            数值: 2
            触发: 绝招时

  - 名称: 妙手仁心
    成员:
      - 2 # 程靈素
      - 28 # 平一指
      - 16 # 胡青牛
      - 45  # 薛慕華
    阈值:
      - 人数: 2
        名称: 悬壶济世
        效果:
          - 类型: 群体施治
            数值: 105
            触发: 绝招时
          - 类型: 群体施治百分比
            数值: 4
            触发: 攻击命中时概率
            触发参数: 10
      - 人数: 4
        名称: 妙手仁心
        效果:
          - 类型: 群体施治
            数值: 150
            触发: 绝招时
          - 类型: 群体施治百分比
            数值: 5
            触发: 攻击命中时概率
            触发参数: 15

  - 名称: 回光返照
    成员:
      - 129  # 王重陽
      - 37  # 狄云
      - 16 # 胡青牛
      - 117  # 天山童姥
    阈值:
      - 人数: 2
        名称: 神照护体
        效果:
          - 类型: 死亡庇护
            数值: 120

  - 名称: 乾坤挪移
    成员:
      - 9 # 張無忌
      - 11 # 楊逍
    阈值:
      - 人数: 2
        名称: 乾坤挪移
        效果:
          - 类型: 保护挪移
            数值: 1
          - 类型: 处决挪移
            数值: 1

  - 名称: 江湖龙套
    成员:
      - 160  # 達爾巴
      - 106 # 王元霸
      - 610  # 俞岱巖
      - 172 # 莫聲谷
      - 124 # 譚處端
      - 72 # 田歸農
      - 608 # 張松溪
      - 126 # 王處一
      - 116  # 無崖子
    阈值:
      - 人数: 2
        名称: 跑龙套
        效果:
          - 类型: 殉爆
            数值: 17
            附加参数: 30
      - 人数: 4
        名称: 炮灰
        效果:
          - 类型: 殉爆
            数值: 25
            附加参数: 46
      - 人数: 6
        名称: 逆袭
        效果:
          - 类型: 殉爆
            数值: 33
            附加参数: 62
