羁绊:
  - 名称: 江南七怪
    成员:
      - 130  # 柯鎮惡
      - 131  # 朱聰
      - 132  # 韓寶駒
      - 133  # 南希仁
      - 134  # 張阿生
      - 135  # 全金發
      - 136  # 韓小瑩
    星级羁绊加成: true
    阈值:
      - 人数: 3
        名称: 七怪合力
        效果:
          - 类型: 防御加成
            数值: 50
          - 类型: 固定减伤
            数值: 15
      - 人数: 5
        名称: 师徒之情
        效果:
          - 类型: 防御加成
            数值: 70
          - 类型: 固定减伤
            数值: 20
      - 人数: 7
        名称: 七侠齐心
        效果:
          - 类型: 防御加成
            数值: 90
          - 类型: 固定减伤
            数值: 25
          - 类型: 格挡几率
            数值: 15

  - 名称: 神雕侠侣
    成员:
      - 58  # 楊過
      - 59  # 小龍女
    阈值:
      - 人数: 2
        名称: 玉女素心
        效果:
          - 类型: 攻击百分比
            数值: 20
          - 类型: 速度加成
            数值: 20
          - 类型: 攻击百分比
            数值: 100
            触发: 友方低血狂暴
            触发参数: 30
            持续帧数: 300
            次数: 1

  - 名称: 姑苏慕容
    成员:
      - 104  # 阿朱
      - 105  # 阿碧
      - 51  # 慕容復
      - 113  # 慕容博
    阈值:
      - 人数: 2
        名称: 参合庄
        效果:
          - 类型: 生命加成
            数值: 200
          - 类型: 技能反弹
            数值: 25
      - 人数: 4
        名称: 以彼之道还施彼身
        效果:
          - 类型: 生命加成
            数值: 350
          - 类型: 攻击百分比
            数值: 25
          - 类型: 技能反弹
            数值: 40

  - 名称: 天龙三兄弟
    成员:
      - 53  # 段譽
      - 49  # 虛竹
      - 50  # 喬峰
    阈值:
      - 人数: 2
        名称: 义结金兰
        效果:
          - 类型: 生命加成
            数值: 300
          - 类型: 回蓝加成
            数值: 25
      - 人数: 3
        名称: 天龙聚首
        效果:
          - 类型: 生命加成
            数值: 500
          - 类型: 回蓝加成
            数值: 100
          - 类型: 僵直抗性
            数值: 50

  - 名称: 五绝
    成员:
      - 57  # 黃藥師
      - 60  # 歐陽鋒
      - 69  # 洪七公
      - 65  # 一燈
      - 64  # 周伯通
    阈值:
      - 人数: 2
        名称: 华山论剑
        效果:
          - 类型: 攻击百分比
            数值: 15
          - 类型: 防御加成
            数值: 50
          - 类型: 速度加成
            数值: 30
      - 人数: 4
        名称: 天下五绝
        效果:
          - 类型: 攻击百分比
            数值: 30
          - 类型: 防御加成
            数值: 100
          - 类型: 速度加成
            数值: 30
          - 类型: 僵直护盾
            数值: 80

  - 名称: 逍遥
    成员:
      - 45  # 薛慕華
      - 115  # 蘇星河
      - 49  # 虛竹
      - 117  # 天山童姥
      - 118  # 李秋水
      - 116  # 無崖子
    阈值:
      - 人数: 2
        名称: 逍遥门徒
        效果:
          - 类型: 速度加成
            数值: 30
          - 类型: 僵直抗性
            数值: 30
      - 人数: 4
        名称: 逍遥无相
        效果:
          - 类型: 速度加成
            数值: 45
          - 类型: 僵直抗性
            数值: 50
          - 类型: 冷却缩减
            数值: 20
      - 人数: 6
        名称: 逍遥至尊
        效果:
          - 类型: 速度加成
            数值: 60
          - 类型: 冷却缩减
            数值: 40
          - 类型: 僵直抗性
            数值: 100
          - 类型: 技能后无敌
            数值: 10

  - 名称: 大理段氏
    成员:
      - 102  # 枯榮
      - 53  # 段譽
      - 98  # 段延慶
      - 65  # 一燈
    阈值:
      - 人数: 2
        名称: 一阳指传承
        效果:
          - 类型: 回蓝加成
            数值: 40
          - 类型: 技能伤害
            数值: 15
      - 人数: 4
        名称: 六脉神剑
        效果:
          - 类型: 回蓝加成
            数值: 80
          - 类型: 技能伤害
            数值: 30
          - 类型: 连击蓄力
            数值: 5
            附加参数: 7 

  - 名称: 四大恶人
    成员:
      - 98  # 段延慶
      - 99  # 葉二娘
      - 44  # 岳老三
      - 100  # 云中鶴
    阈值:
      - 人数: 2
        名称: 恶人当道
        效果:
          - 类型: 攻击百分比
            数值: 35
          - 类型: 防御削减
            数值: 10
          - 类型: 每N次双倍
            数值: 4
      - 人数: 4
        名称: 四大恶人
        效果:
          - 类型: 攻击百分比
            数值: 55
          - 类型: 防御削减
            数值: 20
          - 类型: 每N次双倍
            数值: 3

  - 名称: 桃花岛
    成员:
      - 63  # 程英
      - 56  # 黃蓉
      - 55  # 郭靖
      - 57  # 黃藥師
    阈值:
      - 人数: 2
        名称: 桃花门徒
        效果:
          - 类型: 速度加成
            数值: 30
          - 类型: 闪避几率
            数值: 20
      - 人数: 4
        名称: 桃花岛主
        效果:
          - 类型: 速度加成
            数值: 40
          - 类型: 闪避几率
            数值: 30
          - 类型: 闪避后暴击
            数值: 1

  - 名称: 少林寺
    成员:
      - 70  # 玄慈
      - 103  # 鳩摩智
      - 114  # 掃地老僧
    阈值:
      - 人数: 2
        名称: 少林弟子
        效果:
          - 类型: 生命百分比
            数值: 15
          - 类型: 固定减伤
            数值: 12
          - 类型: 生命回复
            数值: 2
            附加参数: 80
      - 人数: 3
        名称: 扫地神功
        效果:
          - 类型: 生命百分比
            数值: 25
          - 类型: 固定减伤
            数值: 24
          - 类型: 生命回复
            数值: 3
            附加参数: 80
          - 类型: 适应
            数值: 5
            附加参数: 7

  - 名称: 全真教
    成员:
      - 68  # 丘處機
      - 64  # 周伯通
      - 129  # 王重陽
    阈值:
      - 人数: 3
        名称: 先天功
        效果:
          - 类型: 护盾生命比
            数值: 35
          - 类型: 防御加成
            数值: 50
          - 类型: 护盾僵直抗性
            数值: 100

  - 名称: 蒙古三雄
    成员:
      - 84  # 霍都
      - 160  # 達爾巴
      - 62  # 金輪法王
    阈值:
      - 人数: 2
        名称: 蒙古勇士
        效果:
          - 类型: 攻击加成
            数值: 35
          - 类型: 生命加成
            数值: 220
          - 类型: 眩晕几率
            数值: 10
            附加参数: 30
      - 人数: 3
        名称: 龙象之力
        效果:
          - 类型: 攻击加成
            数值: 70
          - 类型: 生命加成
            数值: 440
          - 类型: 眩晕几率
            数值: 25
            附加参数: 40

  - 名称: 连城诀
    成员:
      - 37  # 狄云
      - 97  # 血刀老祖
    阈值:
      - 人数: 2
        名称: 绝境求生
        效果:
          - 类型: 攻击加成
            数值: 100
            触发: 低血量
            触发参数: 50
          - 类型: 回血
            数值: 20
            触发: 低血量
            触发参数: 20
            次数: 1
          - 类型: 攻击百分比
            数值: 30
            触发: 低血量
            触发参数: 40

  - 名称: 毒宗
    成员:
      - 161  # 李莫愁
      - 47  # 阿紫
      - 46  # 丁春秋
      - 60  # 歐陽鋒
    阈值:
      - 人数: 2
        名称: 毒手
        效果:
          - 类型: 中毒伤害
            数值: 5
            附加参数: 90
          - 类型: 僵直抗性
            数值: 20
      - 人数: 4
        名称: 天下毒尊
        效果:
          - 类型: 技能伤害
            数值: 10
          - 类型: 中毒伤害
            数值: 7
            附加参数: 150
          - 类型: 中毒增伤
            数值: 30
          - 类型: 僵直抗性
            数值: 20

  - 名称: 三大吸功
    成员:
      - 48  # 游坦之
      - 53  # 段譽
      - 49  # 虛竹
      - 116  # 無崖子
      - 46  # 丁春秋
    阈值:
      - 人数: 2
        名称: 吸星大法
        效果:
          - 类型: 命中回蓝
            数值: 14
      - 人数: 4
        名称: 北冥神功
        效果:
          - 类型: 命中回蓝
            数值: 15
          - 类型: 吸取内力
            数值: 15
          - 类型: 护盾生命比
            数值: 15

  - 名称: 射雕英雄
    成员:
      - 55  # 郭靖
      - 58  # 楊過
      - 69  # 洪七公
    阈值:
      - 人数: 3
        名称: 为国为民
        效果:
          - 类型: 生命加成
            数值: 500
          - 类型: 击杀回血
            数值: 30
          - 类型: 击杀无敌
            数值: 90

  - 名称: 武林外道
    成员:
      - 67  # 裘千仞
      - 103  # 鳩摩智
      - 62  # 金輪法王
    阈值:
      - 人数: 3
        名称: 以力破巧
        效果:
          - 类型: 攻击加成
            数值: 100
          - 类型: 技能伤害
            数值: 25
          - 类型: 嗜血
            数值: 50

  - 名称: 剑客
    成员:
      - 131  # 朱聰
      - 135  # 全金發
      - 136  # 韓小瑩
      - 63  # 程英
      - 54  # 袁承志
      - 99  # 葉二娘
      - 68  # 丘處機
      - 59  # 小龍女
      - 51  # 慕容復
    阈值:
      - 人数: 3
        名称: 剑意初成
        效果:
          - 类型: 攻击百分比
            数值: 25
          - 类型: 冷却缩减
            数值: 20
          - 类型: 穿甲几率
            数值: 40
          - 类型: 穿甲百分比
            数值: 60
      - 人数: 6
        名称: 万剑归宗
        效果:
          - 类型: 攻击百分比
            数值: 45
          - 类型: 冷却缩减
            数值: 40
          - 类型: 穿甲几率
            数值: 80
          - 类型: 穿甲百分比
            数值: 60

  - 名称: 拳师
    成员:
      - 134  # 張阿生
      - 160  # 達爾巴
      - 84  # 霍都
      - 161  # 李莫愁
      - 45  # 薛慕華
      - 54  # 袁承志
      - 37  # 狄云
      - 48  # 游坦之
      - 100  # 云中鶴
      - 102  # 枯榮
      - 67  # 裘千仞
      - 70  # 玄慈
      - 112  # 蕭遠山
      - 113  # 慕容博
      - 50  # 喬峰
      - 117  # 天山童姥
    阈值:
      - 人数: 3
        名称: 拳意
        效果:
          - 类型: 攻击加成
            数值: 35
          - 类型: 生命加成
            数值: 200
          - 类型: 击退几率
            数值: 12
      - 人数: 6
        名称: 拳圣
        效果:
          - 类型: 攻击加成
            数值: 70
          - 类型: 生命加成
            数值: 350
          - 类型: 攻击百分比
            数值: 10
          - 类型: 击退几率
            数值: 20

  - 名称: 奇门
    成员:
      - 130  # 柯鎮惡
      - 132  # 韓寶駒
      - 133  # 南希仁
      - 44  # 岳老三
    阈值:
      - 人数: 2
        名称: 奇门异术
        效果:
          - 类型: 攻击百分比
            数值: 25
          - 类型: 暴击几率
            数值: 30
      - 人数: 4
        名称: 奇门大成
        效果:
          - 类型: 攻击百分比
            数值: 35
          - 类型: 暴击几率
            数值: 35
          - 类型: 暴击伤害
            数值: 250

  - 名称: 红颜
    成员:
      - 47  # 阿紫
      - 104  # 阿朱
      - 105  # 阿碧
      - 56  # 黃蓉
      - 118  # 李秋水
    阈值:
      - 人数: 2
        名称: 巾帼
        效果:
          - 类型: 速度加成
            数值: 15
          - 类型: 防御百分比
            数值: 20
          - 类型: 固定治疗光环
            数值: 10
            附加参数: 120
          - 类型: 治疗光环
            数值: 2
            附加参数: 120
      - 人数: 4
        名称: 红颜知己
        效果:
          - 类型: 速度加成
            数值: 25
          - 类型: 防御百分比
            数值: 35
          - 类型: 固定治疗光环
            数值: 20
            附加参数: 120 
          - 类型: 治疗光环
            数值: 3
            附加参数: 120
          - 类型: 受治疗加速
            数值: 30

  - 名称: 琴棋书画
    成员:
      - 115  # 蘇星河
      - 57  # 黃藥師
    阈值:
      - 人数: 2
        名称: 博学多才
        效果:
          - 类型: 冷却缩减
            数值: 15
          - 类型: 技能伤害
            数值: 22

  - 名称: 独行
    成员:
      - 97  # 血刀老祖
      - 67  # 裘千仞
      - 98  # 段延慶
      - 112  # 蕭遠山
      - 60  # 歐陽鋒
      - 114  # 掃地老僧
      - 129  # 王重陽
    反向羁绊: true
    阈值:
      - 人数: 1
        名称: 绝世独立
        效果:
          - 类型: 攻击百分比
            数值: 25
          - 类型: 速度加成
            数值: 15
          - 类型: 伤害减免
            数值: 20
          - 类型: 攻击百分比
            数值: 25
            触发: 最后存活
          - 类型: 伤害减免
            数值: 25
            触发: 最后存活
