角色:
  # 费用: 1
  - 130  # 柯鎮惡
  - 131  # 朱聰
  - 132  # 韓寶駒
  - 133  # 南希仁
  - 134  # 張阿生
  - 135  # 全金發
  - 136  # 韓小瑩
  - 84  # 霍都
  - 160  # 達爾巴
  - 104  # 阿朱
  - 105  # 阿碧
  - 72  # 田歸農
  - 4  # 閻基
  - 106  # 王元霸
  - 610  # 俞岱巖
  - 614  # 李文秀
  # 费用: 2
  - 54  # 袁承志
  - 77  # 蕭中慧
  - 82  # 宋青書
  - 613  # 袁冠南
  - 607  # 黛綺絲
  - 172  # 莫聲谷
  # 费用: 3
  - 67  # 裘千仞
  - 51  # 慕容復
  - 103  # 鳩摩智
  - 113  # 慕容博
  - 593  # 周芷若
  - 11  # 楊逍
  - 6  # 滅絕
  - 10  # 范遙
  - 608  # 張松溪
  - 609  # 俞蓮舟
  - 1  # 胡斐
  - 18  # 成崑
  - 19  # 岳不群
  # 费用: 4
  - 38  # 石破天
  - 62  # 金輪法王
  - 9  # 張無忌
  - 13  # 謝遜
  - 171  # 宋遠橋
  - 611  # 無色禪師
  - 603  # 郭襄
  # 费用: 5
  - 114  # 掃地老僧
  - 27  # 東方不敗
  - 604  # 黃裳
  - 5  # 張三丰
