羁绊:
  - 名称: 江南七怪
    成员: [柯鎮惡, 朱聰, 韓寶駒, 南希仁, 張阿生, 全金發, 韓小瑩]
    星级羁绊加成: true
    阈值:
      - 人数: 3
        名称: 七怪合力
        效果:
          - 类型: 防御加成
            数值: 55
          - 类型: 固定减伤
            数值: 20
      - 人数: 5
        名称: 师徒之情
        效果:
          - 类型: 防御加成
            数值: 85
          - 类型: 固定减伤
            数值: 35
      - 人数: 7
        名称: 七侠齐心
        效果:
          - 类型: 防御加成
            数值: 115
          - 类型: 固定减伤
            数值: 35
          - 类型: 格挡几率
            数值: 30

  - 名称: 神雕侠侣
    成员: [楊過, 小龍女]
    阈值:
      - 人数: 2
        名称: 玉女素心
        效果:
          - 类型: 攻击百分比
            数值: 20
          - 类型: 速度加成
            数值: 20
          - 类型: 攻击百分比
            数值: 100
            触发: 友方低血狂暴
            触发参数: 30
            持续帧数: 300
            次数: 1

  - 名称: 姑苏慕容
    成员: [阿朱, 阿碧, 慕容復, 慕容博]
    阈值:
      - 人数: 2
        名称: 参合庄
        效果:
          - 类型: 生命加成
            数值: 150
          - 类型: 技能反弹
            数值: 25
      - 人数: 4
        名称: 以彼之道还施彼身
        效果:
          - 类型: 生命加成
            数值: 350
          - 类型: 攻击百分比
            数值: 25
          - 类型: 技能反弹
            数值: 40

  - 名称: 天龙三兄弟
    成员: [段譽, 虛竹, 喬峰]
    阈值:
      - 人数: 2
        名称: 义结金兰
        效果:
          - 类型: 生命加成
            数值: 300
          - 类型: 回蓝加成
            数值: 25
      - 人数: 3
        名称: 天龙聚首
        效果:
          - 类型: 生命加成
            数值: 500
          - 类型: 回蓝加成
            数值: 100
          - 类型: 僵直抗性
            数值: 50

  - 名称: 五绝
    成员: [黃藥師, 歐陽鋒, 洪七公, 一燈, 周伯通]
    阈值:
      - 人数: 2
        名称: 华山论剑
        效果:
          - 类型: 攻击百分比
            数值: 15
          - 类型: 防御加成
            数值: 50
          - 类型: 速度加成
            数值: 30
      - 人数: 4
        名称: 天下五绝
        效果:
          - 类型: 攻击百分比
            数值: 30
          - 类型: 防御加成
            数值: 100
          - 类型: 速度加成
            数值: 30
          - 类型: 免控帧数
            数值: 15

  - 名称: 逍遥
    成员: [薛慕華, 蘇星河, 虛竹, 天山童姥, 李秋水, 無崖子]
    阈值:
      - 人数: 2
        名称: 逍遥门徒
        效果:
          - 类型: 速度加成
            数值: 30
          - 类型: 僵直抗性
            数值: 30
      - 人数: 4
        名称: 逍遥无相
        效果:
          - 类型: 速度加成
            数值: 45
          - 类型: 僵直抗性
            数值: 50
          - 类型: 冷却缩减
            数值: 20
      - 人数: 6
        名称: 逍遥至尊
        效果:
          - 类型: 速度加成
            数值: 60
          - 类型: 冷却缩减
            数值: 40
          - 类型: 僵直抗性
            数值: 100
          - 类型: 技能后无敌
            数值: 10

  - 名称: 大理段氏
    成员: [枯榮, 段譽, 段延慶, 一燈]
    阈值:
      - 人数: 2
        名称: 一阳指传承
        效果:
          - 类型: 回蓝加成
            数值: 40
          - 类型: 技能伤害
            数值: 15
      - 人数: 4
        名称: 六脉神剑
        效果:
          - 类型: 回蓝加成
            数值: 80
          - 类型: 技能伤害
            数值: 35

  - 名称: 四大恶人
    成员: [段延慶, 葉二娘, 岳老三, 云中鶴]
    阈值:
      - 人数: 2
        名称: 恶人当道
        效果:
          - 类型: 攻击百分比
            数值: 35
          - 类型: 防御削减
            数值: 10
          - 类型: 每N次双倍
            数值: 4
      - 人数: 4
        名称: 四大恶人
        效果:
          - 类型: 攻击百分比
            数值: 55
          - 类型: 防御削减
            数值: 20
          - 类型: 每N次双倍
            数值: 3

  - 名称: 桃花岛
    成员: [程英, 黃蓉, 郭靖, 黃藥師]
    阈值:
      - 人数: 2
        名称: 桃花门徒
        效果:
          - 类型: 速度加成
            数值: 30
          - 类型: 闪避几率
            数值: 25
      - 人数: 4
        名称: 桃花岛主
        效果:
          - 类型: 速度加成
            数值: 40
          - 类型: 闪避几率
            数值: 35
          - 类型: 闪避后暴击
            数值: 1

  - 名称: 少林寺
    成员: [玄慈, 鳩摩智, 掃地老僧]
    阈值:
      - 人数: 2
        名称: 少林弟子
        效果:
          - 类型: 生命百分比
            数值: 15
          - 类型: 固定减伤
            数值: 25
          - 类型: 生命回复
            数值: 2
            附加参数: 60
      - 人数: 3
        名称: 扫地神功
        效果:
          - 类型: 生命百分比
            数值: 25
          - 类型: 固定减伤
            数值: 25
          - 类型: 生命回复
            数值: 3
            附加参数: 60
          - 类型: 适应
            数值: 5
            附加参数: 6

  - 名称: 全真教
    成员: [丘處機, 周伯通, 王重陽]
    阈值:
      - 人数: 3
        名称: 先天功
        效果:
          - 类型: 护盾生命比
            数值: 30
          - 类型: 防御加成
            数值: 50
          - 类型: 护盾僵直抗性
            数值: 100

  - 名称: 蒙古三雄
    成员: [霍都, 達爾巴, 金輪法王]
    阈值:
      - 人数: 2
        名称: 蒙古勇士
        效果:
          - 类型: 攻击加成
            数值: 35
          - 类型: 生命加成
            数值: 220
          - 类型: 眩晕几率
            数值: 10
            附加参数: 30
      - 人数: 3
        名称: 龙象之力
        效果:
          - 类型: 攻击加成
            数值: 70
          - 类型: 生命加成
            数值: 440
          - 类型: 眩晕几率
            数值: 25
            附加参数: 40

  - 名称: 连城诀
    成员: [狄云, 血刀老祖]
    阈值:
      - 人数: 2
        名称: 绝境求生
        效果:
          - 类型: 攻击加成
            数值: 100
            触发: 低血量
            触发参数: 50
          - 类型: 回血
            数值: 20
            触发: 低血量
            触发参数: 20
            次数: 1
          - 类型: 攻击百分比
            数值: 30
            触发: 低血量
            触发参数: 40

  - 名称: 毒宗
    成员: [李莫愁, 阿紫, 丁春秋, 歐陽鋒]
    阈值:
      - 人数: 2
        名称: 毒手
        效果:
          - 类型: 中毒伤害
            数值: 5
            附加参数: 90
      - 人数: 4
        名称: 天下毒尊
        效果:
          - 类型: 中毒伤害
            数值: 7
            附加参数: 150
          - 类型: 中毒增伤
            数值: 30

  - 名称: 三大吸功
    成员: [游坦之, 段譽, 虛竹, 無崖子, 丁春秋]
    阈值:
      - 人数: 2
        名称: 吸星大法
        效果:
          - 类型: 命中回蓝
            数值: 14
      - 人数: 4
        名称: 北冥神功
        效果:
          - 类型: 命中回蓝
            数值: 22
          - 类型: 吸取内力
            数值: 8

  - 名称: 射雕英雄
    成员: [郭靖, 楊過, 洪七公]
    阈值:
      - 人数: 3
        名称: 为国为民
        效果:
          - 类型: 生命加成
            数值: 500
          - 类型: 击杀回血
            数值: 30
          - 类型: 击杀无敌
            数值: 60

  - 名称: 武林外道
    成员: [裘千仞, 鳩摩智, 金輪法王]
    阈值:
      - 人数: 3
        名称: 以力破巧
        效果:
          - 类型: 攻击加成
            数值: 100
          - 类型: 技能伤害
            数值: 25
          - 类型: 嗜血
            数值: 50

  - 名称: 剑客
    成员: [朱聰, 全金發, 韓小瑩, 程英, 袁承志, 葉二娘, 丘處機, 小龍女, 慕容復]
    阈值:
      - 人数: 3
        名称: 剑意初成
        效果:
          - 类型: 攻击百分比
            数值: 25
          - 类型: 速度加成
            数值: 20
          - 类型: 穿甲几率
            数值: 40
          - 类型: 穿甲百分比
            数值: 60
      - 人数: 6
        名称: 万剑归宗
        效果:
          - 类型: 攻击百分比
            数值: 45
          - 类型: 速度加成
            数值: 35
          - 类型: 穿甲几率
            数值: 80
          - 类型: 穿甲百分比
            数值: 60

  - 名称: 拳师
    成员: [張阿生, 達爾巴, 霍都, 李莫愁, 薛慕華, 袁承志, 狄云, 游坦之, 云中鶴, 枯榮, 裘千仞, 玄慈, 蕭遠山, 慕容博, 喬峰, 天山童姥]
    阈值:
      - 人数: 3
        名称: 拳意
        效果:
          - 类型: 攻击加成
            数值: 30
          - 类型: 生命加成
            数值: 200
          - 类型: 击退几率
            数值: 12
      - 人数: 6
        名称: 拳圣
        效果:
          - 类型: 攻击加成
            数值: 70
          - 类型: 生命加成
            数值: 400
          - 类型: 攻击百分比
            数值: 10
          - 类型: 击退几率
            数值: 20

  - 名称: 奇门
    成员: [柯鎮惡, 韓寶駒, 南希仁, 岳老三]
    阈值:
      - 人数: 2
        名称: 奇门异术
        效果:
          - 类型: 攻击百分比
            数值: 25
          - 类型: 暴击几率
            数值: 30
      - 人数: 4
        名称: 奇门大成
        效果:
          - 类型: 攻击百分比
            数值: 35
          - 类型: 暴击几率
            数值: 35
          - 类型: 暴击伤害
            数值: 250

  - 名称: 红颜
    成员: [阿紫, 阿朱, 阿碧, 黃蓉, 李秋水]
    阈值:
      - 人数: 2
        名称: 巾帼
        效果:
          - 类型: 速度加成
            数值: 15
          - 类型: 防御百分比
            数值: 20
          - 类型: 固定治疗光环
            数值: 10
            附加参数: 120
          - 类型: 治疗光环
            数值: 2
            附加参数: 120
      - 人数: 4
        名称: 红颜知己
        效果:
          - 类型: 速度加成
            数值: 25
          - 类型: 防御百分比
            数值: 30
          - 类型: 固定治疗光环
            数值: 20
            附加参数: 120 
          - 类型: 治疗光环
            数值: 2
            附加参数: 120
          - 类型: 受治疗加速
            数值: 30

  - 名称: 琴棋书画
    成员: [蘇星河, 黃藥師]
    阈值:
      - 人数: 2
        名称: 博学多才
        效果:
          - 类型: 冷却缩减
            数值: 15
          - 类型: 技能伤害
            数值: 22

  - 名称: 独行
    成员: [血刀老祖, 裘千仞, 段延慶, 蕭遠山, 歐陽鋒, 掃地老僧, 王重陽]
    反向羁绊: true
    阈值:
      - 人数: 1
        名称: 绝世独立
        效果:
          - 类型: 攻击百分比
            数值: 25
          - 类型: 速度加成
            数值: 15
          - 类型: 伤害减免
            数值: 15
          - 类型: 攻击百分比
            数值: 25
            触发: 最后存活
          - 类型: 伤害减免
            数值: 25
            触发: 最后存活
