# 棋子平衡测试配置
# 使用控制台命令 "test" 启动测试战斗

战场ID: 6          # 对应 DynamicChessMap 中的 battle_id，-1 为随机选择
随机种子: 12345      # 战斗随机种子，-1 为不固定

我方:
  - 角色: 50        # 喬峰
    星级: 1
  - 角色: 55        # 郭靖
    星级: 3
  - 角色: 55        # 郭靖
    星级: 2
  - 角色: 55        # 郭靖
    星级: 2
  - 角色: 55        # 郭靖
    星级: 2
  - 角色: 55        # 郭靖
    星级: 2

敌方:
  - 角色: 60        # 歐陽鋒
    星级: 3
  - 角色: 62        # 金輪法王
    星级: 3
  - 角色: 46        # 丁春秋
    星级: 2
  - 角色: 98        # 段延慶
    星级: 2
  - 角色: 51        # 慕容復
    星级: 2


内功:                # 仅应用于我方，填入武功ID（参考 chess_neigong.yaml）
  - 89              # 紫霞神功
  - 93              # 圣火
