- 费用: 1
  角色:
    - 45  # 薛慕華
    - 63  # 程英
    - 104  # 阿朱
    - 105  # 阿碧
    - 130  # 柯鎮惡
    - 131  # 朱聰
    - 132  # 韓寶駒
    - 133  # 南希仁
    - 134  # 張阿生
    - 135  # 全金發
    - 136  # 韓小瑩
    - 72 # 田歸農
    - 4 # 閻基
    - 106 # 王元霸
    - 605 # 趙敏
    - 618  # 俞岱岩
    - 2 # 程靈素
    - 123 # 馬鈺
    - 124 # 譚處端

- 费用: 2
  角色:
    - 37  # 狄云
    - 44  # 岳老三
    - 48  # 游坦之
    - 56  # 黃蓉
    - 97  # 血刀老祖
    - 99  # 葉二娘
    - 100  # 云中鶴
    - 102  # 枯榮
    - 115  # 蘇星河
    - 29 # 田伯光
    - 82 # 宋青書
    - 607 # 黛綺絲
    - 172 # 莫聲谷
    - 28 # 平一指
    - 16 # 胡青牛
    - 126 # 王處一
    - 125 # 劉處玄

- 费用: 3
  角色:
    - 51  # 慕容復
    - 53  # 段譽
    - 55  # 郭靖
    - 59  # 小龍女
    - 68  # 丘處機
    - 70  # 玄慈
    - 98  # 段延慶
    - 113  # 慕容博
    - 14 # 韋一笑
    - 593 # 周芷若
    - 11 # 楊逍
    - 6 # 滅絕師太
    - 10 # 范遙
    - 608 # 張松溪
    - 609 # 俞蓮舟
    - 1 # 胡斐
    - 18 # 成崑
    - 19 # 岳不群

- 费用: 4
  角色:
    - 49  # 虛竹
    - 50  # 喬峰
    - 57  # 黃藥師
    - 58  # 楊過
    - 64  # 周伯通
    - 65  # 一燈
    - 69  # 洪七公
    - 117  # 天山童姥
    - 118  # 李秋水
    - 589 # 胡一刀
    - 9 # 張無忌
    - 13 # 謝遜
    - 12 # 殷天正
    - 171 # 宋遠橋
    - 611 # 無色禪師
    - 603 # 郭襄

- 费用: 5
  角色:
    - 114  # 掃地老僧
    - 116  # 無崖子
    - 129  # 王重陽
    - 27 # 東方不敗
    - 604 # 黃裳
    - 5 # 張三丰
