远征挑战:
  - 名称: "聚贤庄内"
    描述: "挑战乔峰"
    敌人: [[50, 3]]
    奖励:
      - 类型: 获取金币
        数值: 10
      - 类型: 升星1到2
        最高费用: 2
      - 类型: 获取内功
        最高层级: 1

  - 名称: "慕容世家"
    描述: "姑苏慕容一族的挑战"
    敌人: [[51, 1], [104, 2], [105, 2], [113, 1]]
    奖励:
      - 类型: 获取内功
        最高层级: 2
      - 类型: 获取棋子
        最高费用: 3
      - 类型: 升星1到2
        最高费用: 3

  - 名称: "江南七怪"
    描述: "江南七怪齐聚"
    敌人: [[130, 2], [131, 2], [132, 2], [133, 2], [134, 2], [135, 2], [136, 2]]
    奖励:
      - 类型: 获取金币
        数值: 20
      - 类型: 升星2到3
        最高费用: 2
      - 类型: 获取棋子
        最高费用: 4

  - 名称: "五绝论剑"
    描述: "与五绝级别的高手交锋"
    敌人: [[57, 2], [60, 2], [69, 2], [65, 2], [64, 2]]
    奖励:
      - 类型: 升星2到3
        最高费用: 3
      - 类型: 获取内功
        最高层级: 3
      - 类型: 获取金币
        数值: 25

  - 名称: "武林至尊"
    描述: "挑战最强角色"
    敌人: 
      - [129, 2]
      - [114, 2]
      - [116, 2]
      - [50, 2]
      - [117, 2]
      - [62, 2]
      - [58, 2]
    奖励:
      - 类型: 升星2到3
        最高费用: 4
      - 类型: 获取棋子
        最高费用: 5
      - 类型: 获取金币
        数值: 30

  - 名称: "通关战力"
    描述: "此等战力配合内功足以通关"
    敌人: 
      - [70, 3] # 玄慈
      - [67, 2] # 裘千仞
      - [117, 2] # 天山童姥
      - [113, 3] # 慕容博
      - [112, 2] # 蕭遠山
      - [37, 3] # 狄云
      - [53, 3] # 段誉
      - [97, 3] # 血刀老祖 
    奖励:
      - 类型: 获取金币
        数值: 30

  - 名称: "五费神通"
    描述: "五费亲自部署"
    敌人: 
      - [116, 3] # 无崖子
      - [118, 3] # 李秋水
      - [117, 3] # 天山童姥
      - [49, 3]  # 虚竹
      - [115, 3] # 蘇星河
      - [45, 3]  # 薛慕華
      - [114, 3] # 扫地
      - [103, 3] # 鳩摩智
      - [70, 3] # 玄慈
      - [68, 3] # 丘處機
      - [64, 3] # 周伯通
      - [129, 3] # 王重陽
    奖励:
      - 类型: 获取金币
        数值: 30

  - 名称: "万剑齐发"
    描述: "挑战所有剑系角色"
    敌人: 
      - [131, 3]  # 朱聰
      - [135, 3]  # 全金發
      - [136, 3]  # 韓小瑩
      - [63, 3]  # 程英
      - [54, 3]  # 袁承志
      - [99, 3]  # 葉二娘
      - [68, 3]  # 丘處機
      - [59, 3]  # 小龍女
      - [51, 3]  # 慕容復
    奖励:
      - 类型: 获取金币
        数值: 30